<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>disable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Content Remove="Data\fruits.json" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Resources\Examples\AlertExample.txt" />
    <None Remove="Resources\Examples\DropDownMenu.txt" />
    <None Remove="Resources\Examples\DropDownMulti.txt" />
    <None Remove="Resources\Examples\DropDownSingle.txt" />
    <None Remove="Resources\Examples\Form.txt" />
    <None Remove="Resources\Examples\InputControl.txt" />
    <None Remove="Resources\Examples\ListGroup.txt" />
    <None Remove="Resources\Examples\ListGroupCustom.txt" />
    <None Remove="Resources\Examples\ListView.txt" />
    <None Remove="Resources\Examples\ListViewCustom.txt" />
    <None Remove="Resources\Examples\Modal.txt" />
    <None Remove="Resources\Examples\PropertyGrid.txt" />
    <None Remove="Resources\Examples\PropertyGrid_Collections.txt" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Properties\launchSettings.json" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\Examples\Accordion.txt" />
    <EmbeddedResource Include="Resources\Examples\AccordionItem.txt" />
    <EmbeddedResource Include="Resources\Examples\AlertExample.txt" />
    <EmbeddedResource Include="Resources\Examples\CarouselExample.txt" />
    <EmbeddedResource Include="Resources\Examples\DataGrid.txt" />
    <EmbeddedResource Include="Resources\Examples\DropDownMenu.txt" />
    <EmbeddedResource Include="Resources\Examples\DropDownMulti.txt" />
    <EmbeddedResource Include="Resources\Examples\DropDownSingle.txt" />
    <EmbeddedResource Include="Resources\Examples\Form.txt" />
    <EmbeddedResource Include="Resources\Examples\InputControl.txt" />
    <EmbeddedResource Include="Resources\Examples\ListGroup.txt" />
    <EmbeddedResource Include="Resources\Examples\ListGroupCustom.txt" />
    <EmbeddedResource Include="Resources\Examples\ListView.txt" />
    <EmbeddedResource Include="Resources\Examples\ListViewCustom.txt" />
    <EmbeddedResource Include="Resources\Examples\Modal.txt" />
    <EmbeddedResource Include="Resources\Examples\PropertyGrid.txt" />
    <EmbeddedResource Include="Resources\Examples\PropertyGrid_Collections.txt" />
    <EmbeddedResource Include="Resources\fruits.json" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Services\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Shine.Components\Shine.Components.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resources\Examples\Accordion.txt" />
  </ItemGroup>

</Project>
