using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Shine.Generator
{
    [Generator]
    public class EnumStaticPropertyGenerator : IIncrementalGenerator
    {
        public const string DefaultValueAttrName = "DefaultStringValueAttribute";
        private const string ClassNamespaceAttrName = "ClassNamespaceAttribute";
        private const string StringValueAttrName = "StringValueAttribute";

        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            // Find all enum declarations with the ClassNamespace attribute
            IncrementalValuesProvider<EnumDeclarationSyntax> enumDeclarations = context.SyntaxProvider
                .CreateSyntaxProvider(
                    predicate: static (n, _) => n is EnumDeclarationSyntax,
                    transform: static (ctx, _) => (EnumDeclarationSyntax)ctx.Node)
                .Where(static enumDeclaration => enumDeclaration.EnumKeyword.ValueText == "enum" 
                    && enumDeclaration.Identifier.ValueText != null);

            // Combine the enum declarations with the compilation to get semantic information
            IncrementalValueProvider<(Compilation, ImmutableArray<EnumDeclarationSyntax>)> compilationAndEnums
                = context.CompilationProvider.Combine(enumDeclarations.Collect());

            // Generate the static property classes
            context.RegisterSourceOutput(compilationAndEnums,
                static (spc, source) => Execute(spc, source.Item1, source.Item2));
        }

        static void Execute(SourceProductionContext context, Compilation compilation, ImmutableArray<EnumDeclarationSyntax> enums)
        {
            if (enums.IsDefaultOrEmpty)
            {
                return;
            }

            foreach (EnumDeclarationSyntax enumDeclaration in enums)
            {
                SemanticModel semanticModel = compilation.GetSemanticModel(enumDeclaration.SyntaxTree);
                if (semanticModel.GetDeclaredSymbol(enumDeclaration) is not INamedTypeSymbol enumSymbol)
                {
                    continue;
                }
                var enumAttributes = enumSymbol.GetAttributes();
                // Now perform semantic checks here, like looking for the attribute
                if (!enumAttributes.Any(a => a.AttributeClass?.Name == ClassNamespaceAttrName))
                {
                    continue; // Skip enums without the attribute
                }

                string generatedNamespace = enumSymbol.ContainingNamespace.ToDisplayString();
                string generatedClassName = enumSymbol.Name;
                List<string> enumValues = [];

                // Get the specified namespace from the attribute
                var namespaceAttribute = enumAttributes.FirstOrDefault(a => a.AttributeClass?.Name == ClassNamespaceAttrName);
                if (namespaceAttribute?.ConstructorArguments.Length == 1 && namespaceAttribute.ConstructorArguments[0].Value is string specifiedNamespace)
                {
                    generatedNamespace = specifiedNamespace;
                }

                StringBuilder sourceBuilder = new StringBuilder();

                sourceBuilder.AppendLine("// <auto-generated>");
                sourceBuilder.AppendLine("using System;");
                sourceBuilder.AppendLine();

                if (!string.IsNullOrEmpty(generatedNamespace))
                {
                    sourceBuilder.AppendLine($"namespace {generatedNamespace}");
                    sourceBuilder.AppendLine("{");
                }

                sourceBuilder.AppendLine($"    public sealed record {generatedClassName}");
                sourceBuilder.AppendLine("    {");
                sourceBuilder.AppendLine($"        private readonly string _value;");
                sourceBuilder.AppendLine();
                sourceBuilder.AppendLine($"        public {generatedClassName}(string value)");
                sourceBuilder.AppendLine("        {");
                sourceBuilder.AppendLine("            _value = value ?? Default;");
                sourceBuilder.AppendLine("        }");
                sourceBuilder.AppendLine();

                var defaultValue = GetAttributeValue(
                    enumAttributes.FirstOrDefault(a => a.AttributeClass?.Name == DefaultValueAttrName), 
                    string.Empty);

                sourceBuilder.AppendLine($"        public static implicit operator string({generatedClassName} s) => s?._value ?? Default;");
                sourceBuilder.AppendLine($"        public static implicit operator {generatedClassName}(string? s) => new(s);");
                sourceBuilder.AppendLine();

                sourceBuilder.AppendLine($"        public static readonly {generatedClassName} Default = new {generatedClassName}(\"{defaultValue}\");");
                sourceBuilder.AppendLine();

                foreach (var member in enumSymbol.GetMembers().OfType<IFieldSymbol>())
                {
                    if (member.IsConst) // Only process enum members
                    {
                        string fieldName = member.Name;
                        string stringValue = member.Name; // Default to enum member name

                        // Try to get the StringValue attribute
                        var stringValueAttribute = member.GetAttributes()
                            .FirstOrDefault(a => a.AttributeClass?.Name == StringValueAttrName);

                        stringValue = GetAttributeValue(stringValueAttribute, stringValue);
                        enumValues.Add($"{{{fieldName}, {generatedClassName}.{fieldName}}}");

                        sourceBuilder.AppendLine($"        public static readonly {generatedClassName} {fieldName} = new {generatedClassName}(\"{stringValue}\");");
                    }
                }

                sourceBuilder.AppendLine($"        public static readonly Dictionary<string, {generatedClassName}> Values = new(){{{{\"Default\", Default}}, {string.Join(", ", enumValues)}}};");
                sourceBuilder.AppendLine("        public override string ToString() => _value;");
                sourceBuilder.AppendLine("    }");

                if (!string.IsNullOrEmpty(generatedNamespace))
                {
                    sourceBuilder.AppendLine("}");
                }

                context.AddSource($"{generatedClassName}.g.cs", SourceText.From(sourceBuilder.ToString(), Encoding.UTF8));
            }
        }

        /// <summary>
        /// Get attribute value.
        /// </summary>
        /// <param name="attribute"></param>
        /// <param name="defaultValue"></param>
        /// <returns></returns>
        private static string GetAttributeValue(AttributeData attribute, string defaultValue)
        {
            if (attribute?.ConstructorArguments.Length == 1 && attribute.ConstructorArguments[0].Value is string specifiedStringValue)
                return specifiedStringValue;

            return default;
        }
    }
}