using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Security.Cryptography.X509Certificates;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Shine.Generator
{
    [Generator]
    public class EnumStaticPropertyGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            // Find all enum declarations with the ClassNamespace attribute
            IncrementalValuesProvider<EnumDeclarationSyntax> enumDeclarations = context.SyntaxProvider
                .CreateSyntaxProvider(
                    predicate: static (n, _) => n is EnumDeclarationSyntax,
                    transform: static (ctx, _) => (EnumDeclarationSyntax)ctx.Node)
                .Where(static enumDeclaration => enumDeclaration.EnumKeyword.ValueText == "enum" 
                    && enumDeclaration.Identifier.ValueText != null);

            // Combine the enum declarations with the compilation to get semantic information
            IncrementalValueProvider<(Compilation, ImmutableArray<EnumDeclarationSyntax>)> compilationAndEnums
                = context.CompilationProvider.Combine(enumDeclarations.Collect());

            // Generate the static property classes
            context.RegisterSourceOutput(compilationAndEnums,
                static (spc, source) => Execute(spc, source.Item1, source.Item2));
        }

        static void Execute(SourceProductionContext context, Compilation compilation, ImmutableArray<EnumDeclarationSyntax> enums)
        {
            if (enums.IsDefaultOrEmpty)
            {
                return;
            }

            foreach (EnumDeclarationSyntax enumDeclaration in enums)
            {
                SemanticModel semanticModel = compilation.GetSemanticModel(enumDeclaration.SyntaxTree);
                if (semanticModel.GetDeclaredSymbol(enumDeclaration) is not INamedTypeSymbol enumSymbol)
                {
                    continue;
                }

                // Now perform semantic checks here, like looking for the attribute
                if (!enumSymbol.GetAttributes().Any(a => a.AttributeClass?.Name == "ClassNamespaceAttribute"))
                {
                    continue; // Skip enums without the attribute
                }

                string generatedNamespace = enumSymbol.ContainingNamespace.ToDisplayString();
                string generatedClassName = enumSymbol.Name;
                List<string> enumValues = [];

                // Get the specified namespace from the attribute
                var namespaceAttribute = enumSymbol.GetAttributes()
                    .FirstOrDefault(a => a.AttributeClass?.Name == "ClassNamespaceAttribute");
                if (namespaceAttribute?.ConstructorArguments.Length == 1 && namespaceAttribute.ConstructorArguments[0].Value is string specifiedNamespace)
                {
                    generatedNamespace = specifiedNamespace;
                }

                StringBuilder sourceBuilder = new StringBuilder();

                sourceBuilder.AppendLine("// <auto-generated>");
                sourceBuilder.AppendLine("using System;");
                sourceBuilder.AppendLine();

                if (!string.IsNullOrEmpty(generatedNamespace))
                {
                    sourceBuilder.AppendLine($"namespace {generatedNamespace}");
                    sourceBuilder.AppendLine("{");
                }

                sourceBuilder.AppendLine($"    public sealed record {generatedClassName}");
                sourceBuilder.AppendLine("    {");
                sourceBuilder.AppendLine($"        public string Value {{ get; }}");
                sourceBuilder.AppendLine();
                sourceBuilder.AppendLine($"        public {generatedClassName}(string value)");
                sourceBuilder.AppendLine("        {");
                sourceBuilder.AppendLine("            Value = value;");
                sourceBuilder.AppendLine("        }");
                sourceBuilder.AppendLine();

                foreach (var member in enumSymbol.GetMembers().OfType<IFieldSymbol>())
                {
                    if (member.IsConst) // Only process enum members
                    {
                        string fieldName = member.Name;
                        string stringValue = member.Name; // Default to enum member name
                        enumValues.Add($"{generatedClassName}.{fieldName}");

                        // Try to get the StringValue attribute
                        var stringValueAttribute = member.GetAttributes()
                            .FirstOrDefault(a => a.AttributeClass?.Name == "StringValueAttribute");
                        if (stringValueAttribute?.ConstructorArguments.Length == 1 && stringValueAttribute.ConstructorArguments[0].Value is string specifiedStringValue)
                        {
                            stringValue = specifiedStringValue;
                        }

                        sourceBuilder.AppendLine($"        public static {generatedClassName} {fieldName} {{ get; }} = new {generatedClassName}(\"{stringValue}\");");
                    }
                }

                sourceBuilder.AppendLine($"        public static readonly {generatedClassName}[] Values = [{string.Join(",", enumValues)}];");

                sourceBuilder.AppendLine("        public override string ToString() { return Value; }");
                sourceBuilder.AppendLine("    }");

                if (!string.IsNullOrEmpty(generatedNamespace))
                {
                    sourceBuilder.AppendLine("}");
                }

                context.AddSource($"{generatedClassName}.g.cs", SourceText.From(sourceBuilder.ToString(), Encoding.UTF8));
            }
        }
    }
}