<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>disable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Services\**" />
    <Content Remove="Services\**" />
    <EmbeddedResource Remove="Services\**" />
    <None Remove="Services\**" />
  </ItemGroup>

  <ItemGroup>
    <Content Remove="Data\fruits.json" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Resources\Examples\ButtonActions.txt" />
    <None Remove="Resources\Examples\ButtonStyles.txt" />
    <None Remove="Resources\Examples\DropDownMenu.txt" />
    <None Remove="Resources\Examples\DropDownMulti.txt" />
    <None Remove="Resources\Examples\DropDownSingle.txt" />
    <None Remove="Resources\Examples\Form.txt" />
    <None Remove="Resources\Examples\InfiniteScroll.txt" />
    <None Remove="Resources\Examples\InputControl.txt" />
    <None Remove="Resources\Examples\ListGroup.txt" />
    <None Remove="Resources\Examples\ListGroupCustom.txt" />
    <None Remove="Resources\Examples\ListView.txt" />
    <None Remove="Resources\Examples\ListViewCustom.txt" />
    <None Remove="Resources\Examples\Modal.txt" />
    <None Remove="Resources\Examples\PropertyGrid.txt" />
    <None Remove="Resources\Examples\PropertyGrid_Collections.txt" />
    <None Remove="Resources\Examples\Splash.txt" />
    <None Remove="Resources\Examples\ThemeSelector.txt" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Properties\launchSettings.json" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\Examples\Accordion.txt" />
    <EmbeddedResource Include="Resources\Examples\AccordionItem.txt" />
    <EmbeddedResource Include="Resources\Examples\AlertExample.txt" />
    <EmbeddedResource Include="Resources\Examples\ButtonActions.txt" />
    <EmbeddedResource Include="Resources\Examples\ButtonStyles.txt" />
    <EmbeddedResource Include="Resources\Examples\CarouselExample.txt" />
    <EmbeddedResource Include="Resources\Examples\DataGrid.txt" />
    <EmbeddedResource Include="Resources\Examples\DropDownMenu.txt" />
    <EmbeddedResource Include="Resources\Examples\DropDownMulti.txt" />
    <EmbeddedResource Include="Resources\Examples\DropDownSingle.txt" />
    <EmbeddedResource Include="Resources\Examples\Form.txt" />
    <EmbeddedResource Include="Resources\Examples\InfiniteScroll.txt" />
    <EmbeddedResource Include="Resources\Examples\InputControl.txt" />
    <EmbeddedResource Include="Resources\Examples\ListGroup.txt" />
    <EmbeddedResource Include="Resources\Examples\ListGroupCustom.txt" />
    <EmbeddedResource Include="Resources\Examples\ListView.txt" />
    <EmbeddedResource Include="Resources\Examples\ListViewCustom.txt" />
    <EmbeddedResource Include="Resources\Examples\Modal.txt" />
    <EmbeddedResource Include="Resources\Examples\PropertyGrid.txt" />
    <EmbeddedResource Include="Resources\Examples\PropertyGrid_Collections.txt" />
    <EmbeddedResource Include="Resources\Examples\Splash.txt" />
    <EmbeddedResource Include="Resources\Examples\ThemeSelector.txt" />
    <EmbeddedResource Include="Resources\fruits.json" />
  </ItemGroup>

  <ItemGroup>
	  <PackageReference Include="Markdig" Version="0.40.0" />
	  <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="9.0.3" />
	  <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="9.0.3" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ShineBlazor.Components\ShineBlazor.Components.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resources\Examples\Accordion.txt" />
  </ItemGroup>

</Project>
